// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: contracts.v1/release_log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Contracts.V1 {

  /// <summary>Holder for reflection information generated from contracts.v1/release_log.proto</summary>
  public static partial class ReleaseLogReflection {

    #region Descriptor
    /// <summary>File descriptor for contracts.v1/release_log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReleaseLogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5jb250cmFjdHMudjEvcmVsZWFzZV9sb2cucHJvdG8SDGNvbnRyYWN0cy52",
            "MRohY29udHJhY3RzLnYxL2J1aWxkX2xvZ19zdGVwLnByb3RvGh9nb29nbGUv",
            "cHJvdG9idWYvdGltZXN0YW1wLnByb3RvIsQBCgpSZWxlYXNlTG9nEgoKAmlk",
            "GAEgASgJEhMKC3JlcG9fc291cmNlGAIgASgJEhIKCnJlcG9fb3duZXIYAyAB",
            "KAkSEQoJcmVwb19uYW1lGAQgASgJEhIKCnJlbGVhc2VfaWQYBSABKAkSKQoF",
            "c3RlcHMYBiADKAsyGi5jb250cmFjdHMudjEuQnVpbGRMb2dTdGVwEi8KC2lu",
            "c2VydGVkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEJB",
            "Wj9naXRodWIuY29tL2VzdGFmZXR0ZS9lc3RhZmV0dGUtY2ktY29udHJhY3Rz",
            "LWdvbGFuZy9jb250cmFjdHNfdjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Contracts.V1.BuildLogStepReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Contracts.V1.ReleaseLog), global::Contracts.V1.ReleaseLog.Parser, new[]{ "Id", "RepoSource", "RepoOwner", "RepoName", "ReleaseId", "Steps", "InsertedAt" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ReleaseLog : pb::IMessage<ReleaseLog> {
    private static readonly pb::MessageParser<ReleaseLog> _parser = new pb::MessageParser<ReleaseLog>(() => new ReleaseLog());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReleaseLog> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Contracts.V1.ReleaseLogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseLog() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseLog(ReleaseLog other) : this() {
      id_ = other.id_;
      repoSource_ = other.repoSource_;
      repoOwner_ = other.repoOwner_;
      repoName_ = other.repoName_;
      releaseId_ = other.releaseId_;
      steps_ = other.steps_.Clone();
      insertedAt_ = other.insertedAt_ != null ? other.insertedAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseLog Clone() {
      return new ReleaseLog(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "repo_source" field.</summary>
    public const int RepoSourceFieldNumber = 2;
    private string repoSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RepoSource {
      get { return repoSource_; }
      set {
        repoSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "repo_owner" field.</summary>
    public const int RepoOwnerFieldNumber = 3;
    private string repoOwner_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RepoOwner {
      get { return repoOwner_; }
      set {
        repoOwner_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "repo_name" field.</summary>
    public const int RepoNameFieldNumber = 4;
    private string repoName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RepoName {
      get { return repoName_; }
      set {
        repoName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "release_id" field.</summary>
    public const int ReleaseIdFieldNumber = 5;
    private string releaseId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ReleaseId {
      get { return releaseId_; }
      set {
        releaseId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "steps" field.</summary>
    public const int StepsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Contracts.V1.BuildLogStep> _repeated_steps_codec
        = pb::FieldCodec.ForMessage(50, global::Contracts.V1.BuildLogStep.Parser);
    private readonly pbc::RepeatedField<global::Contracts.V1.BuildLogStep> steps_ = new pbc::RepeatedField<global::Contracts.V1.BuildLogStep>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Contracts.V1.BuildLogStep> Steps {
      get { return steps_; }
    }

    /// <summary>Field number for the "inserted_at" field.</summary>
    public const int InsertedAtFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp insertedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp InsertedAt {
      get { return insertedAt_; }
      set {
        insertedAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReleaseLog);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReleaseLog other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (RepoSource != other.RepoSource) return false;
      if (RepoOwner != other.RepoOwner) return false;
      if (RepoName != other.RepoName) return false;
      if (ReleaseId != other.ReleaseId) return false;
      if(!steps_.Equals(other.steps_)) return false;
      if (!object.Equals(InsertedAt, other.InsertedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (RepoSource.Length != 0) hash ^= RepoSource.GetHashCode();
      if (RepoOwner.Length != 0) hash ^= RepoOwner.GetHashCode();
      if (RepoName.Length != 0) hash ^= RepoName.GetHashCode();
      if (ReleaseId.Length != 0) hash ^= ReleaseId.GetHashCode();
      hash ^= steps_.GetHashCode();
      if (insertedAt_ != null) hash ^= InsertedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (RepoSource.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RepoSource);
      }
      if (RepoOwner.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(RepoOwner);
      }
      if (RepoName.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RepoName);
      }
      if (ReleaseId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ReleaseId);
      }
      steps_.WriteTo(output, _repeated_steps_codec);
      if (insertedAt_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(InsertedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (RepoSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoSource);
      }
      if (RepoOwner.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoOwner);
      }
      if (RepoName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoName);
      }
      if (ReleaseId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReleaseId);
      }
      size += steps_.CalculateSize(_repeated_steps_codec);
      if (insertedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InsertedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReleaseLog other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.RepoSource.Length != 0) {
        RepoSource = other.RepoSource;
      }
      if (other.RepoOwner.Length != 0) {
        RepoOwner = other.RepoOwner;
      }
      if (other.RepoName.Length != 0) {
        RepoName = other.RepoName;
      }
      if (other.ReleaseId.Length != 0) {
        ReleaseId = other.ReleaseId;
      }
      steps_.Add(other.steps_);
      if (other.insertedAt_ != null) {
        if (insertedAt_ == null) {
          insertedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        InsertedAt.MergeFrom(other.InsertedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            RepoSource = input.ReadString();
            break;
          }
          case 26: {
            RepoOwner = input.ReadString();
            break;
          }
          case 34: {
            RepoName = input.ReadString();
            break;
          }
          case 42: {
            ReleaseId = input.ReadString();
            break;
          }
          case 50: {
            steps_.AddEntriesFrom(input, _repeated_steps_codec);
            break;
          }
          case 58: {
            if (insertedAt_ == null) {
              insertedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(insertedAt_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
