// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: estafette/ci/manifest/v1/estafette_version.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Estafette.Ci.Manifest.V1 {

  /// <summary>Holder for reflection information generated from estafette/ci/manifest/v1/estafette_version.proto</summary>
  public static partial class EstafetteVersionReflection {

    #region Descriptor
    /// <summary>File descriptor for estafette/ci/manifest/v1/estafette_version.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EstafetteVersionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBlc3RhZmV0dGUvY2kvbWFuaWZlc3QvdjEvZXN0YWZldHRlX3ZlcnNpb24u",
            "cHJvdG8SGGVzdGFmZXR0ZS5jaS5tYW5pZmVzdC52MRo3ZXN0YWZldHRlL2Np",
            "L21hbmlmZXN0L3YxL2VzdGFmZXR0ZV9jdXN0b21fdmVyc2lvbi5wcm90bxo3",
            "ZXN0YWZldHRlL2NpL21hbmlmZXN0L3YxL2VzdGFmZXR0ZV9zZW12ZXJfdmVy",
            "c2lvbi5wcm90byKWAQoQRXN0YWZldHRlVmVyc2lvbhJACgZzZW12ZXIYASAB",
            "KAsyMC5lc3RhZmV0dGUuY2kubWFuaWZlc3QudjEuRXN0YWZldHRlU2VtdmVy",
            "VmVyc2lvbhJACgZjdXN0b20YAiABKAsyMC5lc3RhZmV0dGUuY2kubWFuaWZl",
            "c3QudjEuRXN0YWZldHRlQ3VzdG9tVmVyc2lvbkJ4Chxjb20uZXN0YWZldHRl",
            "LmNpLm1hbmlmZXN0LnYxUAFaO2dpdGh1Yi5jb20vZXN0YWZldHRlL2VzdGFm",
            "ZXR0ZS1jaS1wcm90b3MtZ29sYW5nL21hbmlmZXN0X3YxqgIYRXN0YWZldHRl",
            "LkNpLk1hbmlmZXN0LlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Estafette.Ci.Manifest.V1.EstafetteCustomVersionReflection.Descriptor, global::Estafette.Ci.Manifest.V1.EstafetteSemverVersionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Estafette.Ci.Manifest.V1.EstafetteVersion), global::Estafette.Ci.Manifest.V1.EstafetteVersion.Parser, new[]{ "Semver", "Custom" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EstafetteVersion : pb::IMessage<EstafetteVersion> {
    private static readonly pb::MessageParser<EstafetteVersion> _parser = new pb::MessageParser<EstafetteVersion>(() => new EstafetteVersion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EstafetteVersion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Estafette.Ci.Manifest.V1.EstafetteVersionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteVersion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteVersion(EstafetteVersion other) : this() {
      semver_ = other.semver_ != null ? other.semver_.Clone() : null;
      custom_ = other.custom_ != null ? other.custom_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteVersion Clone() {
      return new EstafetteVersion(this);
    }

    /// <summary>Field number for the "semver" field.</summary>
    public const int SemverFieldNumber = 1;
    private global::Estafette.Ci.Manifest.V1.EstafetteSemverVersion semver_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Estafette.Ci.Manifest.V1.EstafetteSemverVersion Semver {
      get { return semver_; }
      set {
        semver_ = value;
      }
    }

    /// <summary>Field number for the "custom" field.</summary>
    public const int CustomFieldNumber = 2;
    private global::Estafette.Ci.Manifest.V1.EstafetteCustomVersion custom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Estafette.Ci.Manifest.V1.EstafetteCustomVersion Custom {
      get { return custom_; }
      set {
        custom_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EstafetteVersion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EstafetteVersion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Semver, other.Semver)) return false;
      if (!object.Equals(Custom, other.Custom)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (semver_ != null) hash ^= Semver.GetHashCode();
      if (custom_ != null) hash ^= Custom.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (semver_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Semver);
      }
      if (custom_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Custom);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (semver_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Semver);
      }
      if (custom_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Custom);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EstafetteVersion other) {
      if (other == null) {
        return;
      }
      if (other.semver_ != null) {
        if (semver_ == null) {
          Semver = new global::Estafette.Ci.Manifest.V1.EstafetteSemverVersion();
        }
        Semver.MergeFrom(other.Semver);
      }
      if (other.custom_ != null) {
        if (custom_ == null) {
          Custom = new global::Estafette.Ci.Manifest.V1.EstafetteCustomVersion();
        }
        Custom.MergeFrom(other.Custom);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (semver_ == null) {
              Semver = new global::Estafette.Ci.Manifest.V1.EstafetteSemverVersion();
            }
            input.ReadMessage(Semver);
            break;
          }
          case 18: {
            if (custom_ == null) {
              Custom = new global::Estafette.Ci.Manifest.V1.EstafetteCustomVersion();
            }
            input.ReadMessage(Custom);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
