// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/manifest.v1/estafette_version_params.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Estafette.CI.Manifest.V1 {

  /// <summary>Holder for reflection information generated from protos/manifest.v1/estafette_version_params.proto</summary>
  public static partial class EstafetteVersionParamsReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/manifest.v1/estafette_version_params.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EstafetteVersionParamsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFwcm90b3MvbWFuaWZlc3QudjEvZXN0YWZldHRlX3ZlcnNpb25fcGFyYW1z",
            "LnByb3RvEgttYW5pZmVzdC52MSJSChZFc3RhZmV0dGVWZXJzaW9uUGFyYW1z",
            "EhYKDmF1dG9faW5jcmVtZW50GAEgASgDEg4KBmJyYW5jaBgCIAEoCRIQCghy",
            "ZXZpc2lvbhgDIAEoCUJ8CiJpby5lc3RhZmV0dGUuY2kucHJvdG9zLm1hbmlm",
            "ZXN0LnYxWjtnaXRodWIuY29tL2VzdGFmZXR0ZS9lc3RhZmV0dGUtY2ktcHJv",
            "dG9zLWdvbGFuZy9tYW5pZmVzdF92MaoCGEVzdGFmZXR0ZS5DSS5NYW5pZmVz",
            "dC5WMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Estafette.CI.Manifest.V1.EstafetteVersionParams), global::Estafette.CI.Manifest.V1.EstafetteVersionParams.Parser, new[]{ "AutoIncrement", "Branch", "Revision" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EstafetteVersionParams : pb::IMessage<EstafetteVersionParams> {
    private static readonly pb::MessageParser<EstafetteVersionParams> _parser = new pb::MessageParser<EstafetteVersionParams>(() => new EstafetteVersionParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EstafetteVersionParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Estafette.CI.Manifest.V1.EstafetteVersionParamsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteVersionParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteVersionParams(EstafetteVersionParams other) : this() {
      autoIncrement_ = other.autoIncrement_;
      branch_ = other.branch_;
      revision_ = other.revision_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteVersionParams Clone() {
      return new EstafetteVersionParams(this);
    }

    /// <summary>Field number for the "auto_increment" field.</summary>
    public const int AutoIncrementFieldNumber = 1;
    private long autoIncrement_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long AutoIncrement {
      get { return autoIncrement_; }
      set {
        autoIncrement_ = value;
      }
    }

    /// <summary>Field number for the "branch" field.</summary>
    public const int BranchFieldNumber = 2;
    private string branch_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Branch {
      get { return branch_; }
      set {
        branch_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "revision" field.</summary>
    public const int RevisionFieldNumber = 3;
    private string revision_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Revision {
      get { return revision_; }
      set {
        revision_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EstafetteVersionParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EstafetteVersionParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AutoIncrement != other.AutoIncrement) return false;
      if (Branch != other.Branch) return false;
      if (Revision != other.Revision) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AutoIncrement != 0L) hash ^= AutoIncrement.GetHashCode();
      if (Branch.Length != 0) hash ^= Branch.GetHashCode();
      if (Revision.Length != 0) hash ^= Revision.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AutoIncrement != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AutoIncrement);
      }
      if (Branch.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Branch);
      }
      if (Revision.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Revision);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AutoIncrement != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AutoIncrement);
      }
      if (Branch.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Branch);
      }
      if (Revision.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Revision);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EstafetteVersionParams other) {
      if (other == null) {
        return;
      }
      if (other.AutoIncrement != 0L) {
        AutoIncrement = other.AutoIncrement;
      }
      if (other.Branch.Length != 0) {
        Branch = other.Branch;
      }
      if (other.Revision.Length != 0) {
        Revision = other.Revision;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AutoIncrement = input.ReadInt64();
            break;
          }
          case 18: {
            Branch = input.ReadString();
            break;
          }
          case 26: {
            Revision = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
