// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: estafette/ci/manifest/v1/estafette_release.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Estafette.Ci.Manifest.V1 {

  /// <summary>Holder for reflection information generated from estafette/ci/manifest/v1/estafette_release.proto</summary>
  public static partial class EstafetteReleaseReflection {

    #region Descriptor
    /// <summary>File descriptor for estafette/ci/manifest/v1/estafette_release.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EstafetteReleaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjBlc3RhZmV0dGUvY2kvbWFuaWZlc3QvdjEvZXN0YWZldHRlX3JlbGVhc2Uu",
            "cHJvdG8SGGVzdGFmZXR0ZS5jaS5tYW5pZmVzdC52MRo3ZXN0YWZldHRlL2Np",
            "L21hbmlmZXN0L3YxL2VzdGFmZXR0ZV9yZWxlYXNlX2FjdGlvbi5wcm90bxou",
            "ZXN0YWZldHRlL2NpL21hbmlmZXN0L3YxL2VzdGFmZXR0ZV9zdGFnZS5wcm90",
            "bxowZXN0YWZldHRlL2NpL21hbmlmZXN0L3YxL2VzdGFmZXR0ZV90cmlnZ2Vy",
            "LnByb3RvIvUBChBFc3RhZmV0dGVSZWxlYXNlEgwKBG5hbWUYASABKAkSGAoQ",
            "Y2xvbmVfcmVwb3NpdG9yeRgCIAEoCBJBCgdhY3Rpb25zGAMgAygLMjAuZXN0",
            "YWZldHRlLmNpLm1hbmlmZXN0LnYxLkVzdGFmZXR0ZVJlbGVhc2VBY3Rpb24S",
            "PAoIdHJpZ2dlcnMYBCADKAsyKi5lc3RhZmV0dGUuY2kubWFuaWZlc3QudjEu",
            "RXN0YWZldHRlVHJpZ2dlchI4CgZzdGFnZXMYBSADKAsyKC5lc3RhZmV0dGUu",
            "Y2kubWFuaWZlc3QudjEuRXN0YWZldHRlU3RhZ2VCeAocY29tLmVzdGFmZXR0",
            "ZS5jaS5tYW5pZmVzdC52MVABWjtnaXRodWIuY29tL2VzdGFmZXR0ZS9lc3Rh",
            "ZmV0dGUtY2ktcHJvdG9zLWdvbGFuZy9tYW5pZmVzdF92MaoCGEVzdGFmZXR0",
            "ZS5DaS5NYW5pZmVzdC5WMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Estafette.Ci.Manifest.V1.EstafetteReleaseActionReflection.Descriptor, global::Estafette.Ci.Manifest.V1.EstafetteStageReflection.Descriptor, global::Estafette.Ci.Manifest.V1.EstafetteTriggerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Estafette.Ci.Manifest.V1.EstafetteRelease), global::Estafette.Ci.Manifest.V1.EstafetteRelease.Parser, new[]{ "Name", "CloneRepository", "Actions", "Triggers", "Stages" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EstafetteRelease : pb::IMessage<EstafetteRelease> {
    private static readonly pb::MessageParser<EstafetteRelease> _parser = new pb::MessageParser<EstafetteRelease>(() => new EstafetteRelease());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EstafetteRelease> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Estafette.Ci.Manifest.V1.EstafetteReleaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteRelease() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteRelease(EstafetteRelease other) : this() {
      name_ = other.name_;
      cloneRepository_ = other.cloneRepository_;
      actions_ = other.actions_.Clone();
      triggers_ = other.triggers_.Clone();
      stages_ = other.stages_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EstafetteRelease Clone() {
      return new EstafetteRelease(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "clone_repository" field.</summary>
    public const int CloneRepositoryFieldNumber = 2;
    private bool cloneRepository_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool CloneRepository {
      get { return cloneRepository_; }
      set {
        cloneRepository_ = value;
      }
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(26, global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction.Parser);
    private readonly pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction> actions_ = new pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction> Actions {
      get { return actions_; }
    }

    /// <summary>Field number for the "triggers" field.</summary>
    public const int TriggersFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Estafette.Ci.Manifest.V1.EstafetteTrigger> _repeated_triggers_codec
        = pb::FieldCodec.ForMessage(34, global::Estafette.Ci.Manifest.V1.EstafetteTrigger.Parser);
    private readonly pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteTrigger> triggers_ = new pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteTrigger>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteTrigger> Triggers {
      get { return triggers_; }
    }

    /// <summary>Field number for the "stages" field.</summary>
    public const int StagesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Estafette.Ci.Manifest.V1.EstafetteStage> _repeated_stages_codec
        = pb::FieldCodec.ForMessage(42, global::Estafette.Ci.Manifest.V1.EstafetteStage.Parser);
    private readonly pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteStage> stages_ = new pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteStage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteStage> Stages {
      get { return stages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EstafetteRelease);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EstafetteRelease other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (CloneRepository != other.CloneRepository) return false;
      if(!actions_.Equals(other.actions_)) return false;
      if(!triggers_.Equals(other.triggers_)) return false;
      if(!stages_.Equals(other.stages_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (CloneRepository != false) hash ^= CloneRepository.GetHashCode();
      hash ^= actions_.GetHashCode();
      hash ^= triggers_.GetHashCode();
      hash ^= stages_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (CloneRepository != false) {
        output.WriteRawTag(16);
        output.WriteBool(CloneRepository);
      }
      actions_.WriteTo(output, _repeated_actions_codec);
      triggers_.WriteTo(output, _repeated_triggers_codec);
      stages_.WriteTo(output, _repeated_stages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (CloneRepository != false) {
        size += 1 + 1;
      }
      size += actions_.CalculateSize(_repeated_actions_codec);
      size += triggers_.CalculateSize(_repeated_triggers_codec);
      size += stages_.CalculateSize(_repeated_stages_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EstafetteRelease other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.CloneRepository != false) {
        CloneRepository = other.CloneRepository;
      }
      actions_.Add(other.actions_);
      triggers_.Add(other.triggers_);
      stages_.Add(other.stages_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            CloneRepository = input.ReadBool();
            break;
          }
          case 26: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
          case 34: {
            triggers_.AddEntriesFrom(input, _repeated_triggers_codec);
            break;
          }
          case 42: {
            stages_.AddEntriesFrom(input, _repeated_stages_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
