// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: estafette/ci/contracts/v1/release_target.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Estafette.Ci.Contracts.V1 {

  /// <summary>Holder for reflection information generated from estafette/ci/contracts/v1/release_target.proto</summary>
  public static partial class ReleaseTargetReflection {

    #region Descriptor
    /// <summary>File descriptor for estafette/ci/contracts/v1/release_target.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReleaseTargetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5lc3RhZmV0dGUvY2kvY29udHJhY3RzL3YxL3JlbGVhc2VfdGFyZ2V0LnBy",
            "b3RvEhllc3RhZmV0dGUuY2kuY29udHJhY3RzLnYxGidlc3RhZmV0dGUvY2kv",
            "Y29udHJhY3RzL3YxL3JlbGVhc2UucHJvdG8aN2VzdGFmZXR0ZS9jaS9tYW5p",
            "ZmVzdC92MS9lc3RhZmV0dGVfcmVsZWFzZV9hY3Rpb24ucHJvdG8inQEKDVJl",
            "bGVhc2VUYXJnZXQSDAoEbmFtZRgBIAEoCRJBCgdhY3Rpb25zGAIgAygLMjAu",
            "ZXN0YWZldHRlLmNpLm1hbmlmZXN0LnYxLkVzdGFmZXR0ZVJlbGVhc2VBY3Rp",
            "b24SOwoPYWN0aXZlX3JlbGVhc2VzGAMgAygLMiIuZXN0YWZldHRlLmNpLmNv",
            "bnRyYWN0cy52MS5SZWxlYXNlQnsKHWNvbS5lc3RhZmV0dGUuY2kuY29udHJh",
            "Y3RzLnYxUAFaPGdpdGh1Yi5jb20vZXN0YWZldHRlL2VzdGFmZXR0ZS1jaS1w",
            "cm90b3MtZ29sYW5nL2NvbnRyYWN0cy92MaoCGUVzdGFmZXR0ZS5DaS5Db250",
            "cmFjdHMuVjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Estafette.Ci.Contracts.V1.ReleaseReflection.Descriptor, global::Estafette.Ci.Manifest.V1.EstafetteReleaseActionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Estafette.Ci.Contracts.V1.ReleaseTarget), global::Estafette.Ci.Contracts.V1.ReleaseTarget.Parser, new[]{ "Name", "Actions", "ActiveReleases" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ReleaseTarget : pb::IMessage<ReleaseTarget> {
    private static readonly pb::MessageParser<ReleaseTarget> _parser = new pb::MessageParser<ReleaseTarget>(() => new ReleaseTarget());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ReleaseTarget> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Estafette.Ci.Contracts.V1.ReleaseTargetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseTarget() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseTarget(ReleaseTarget other) : this() {
      name_ = other.name_;
      actions_ = other.actions_.Clone();
      activeReleases_ = other.activeReleases_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ReleaseTarget Clone() {
      return new ReleaseTarget(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "actions" field.</summary>
    public const int ActionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction> _repeated_actions_codec
        = pb::FieldCodec.ForMessage(18, global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction.Parser);
    private readonly pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction> actions_ = new pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Estafette.Ci.Manifest.V1.EstafetteReleaseAction> Actions {
      get { return actions_; }
    }

    /// <summary>Field number for the "active_releases" field.</summary>
    public const int ActiveReleasesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Estafette.Ci.Contracts.V1.Release> _repeated_activeReleases_codec
        = pb::FieldCodec.ForMessage(26, global::Estafette.Ci.Contracts.V1.Release.Parser);
    private readonly pbc::RepeatedField<global::Estafette.Ci.Contracts.V1.Release> activeReleases_ = new pbc::RepeatedField<global::Estafette.Ci.Contracts.V1.Release>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Estafette.Ci.Contracts.V1.Release> ActiveReleases {
      get { return activeReleases_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ReleaseTarget);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ReleaseTarget other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!actions_.Equals(other.actions_)) return false;
      if(!activeReleases_.Equals(other.activeReleases_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= actions_.GetHashCode();
      hash ^= activeReleases_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      actions_.WriteTo(output, _repeated_actions_codec);
      activeReleases_.WriteTo(output, _repeated_activeReleases_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += actions_.CalculateSize(_repeated_actions_codec);
      size += activeReleases_.CalculateSize(_repeated_activeReleases_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ReleaseTarget other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      actions_.Add(other.actions_);
      activeReleases_.Add(other.activeReleases_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            actions_.AddEntriesFrom(input, _repeated_actions_codec);
            break;
          }
          case 26: {
            activeReleases_.AddEntriesFrom(input, _repeated_activeReleases_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
