// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: contracts.v1/release.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Estafette.CI.Contracts.V1 {

  /// <summary>Holder for reflection information generated from contracts.v1/release.proto</summary>
  public static partial class ReleaseReflection {

    #region Descriptor
    /// <summary>File descriptor for contracts.v1/release.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReleaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpjb250cmFjdHMudjEvcmVsZWFzZS5wcm90bxIMY29udHJhY3RzLnYxGh5n",
            "b29nbGUvcHJvdG9idWYvZHVyYXRpb24ucHJvdG8aH2dvb2dsZS9wcm90b2J1",
            "Zi90aW1lc3RhbXAucHJvdG8aIW1hbmlmZXN0LnYxL2VzdGFmZXR0ZV9ldmVu",
            "dC5wcm90byLIAgoHUmVsZWFzZRIMCgRuYW1lGAEgASgJEg4KBmFjdGlvbhgC",
            "IAEoCRIKCgJpZBgDIAEoCRITCgtyZXBvX3NvdXJjZRgEIAEoCRISCgpyZXBv",
            "X293bmVyGAUgASgJEhcKD3JlbGVhc2VfdmVyc2lvbhgGIAEoCRIWCg5yZWxl",
            "YXNlX3N0YXR1cxgHIAEoCRIrCgZldmVudHMYCCADKAsyGy5tYW5pZmVzdC52",
            "MS5Fc3RhZmV0dGVFdmVudBIvCgtpbnNlcnRlZF9hdBgJIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgKIAEoCzIaLmdv",
            "b2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKwoIZHVyYXRpb24YCyABKAsyGS5n",
            "b29nbGUucHJvdG9idWYuRHVyYXRpb25CfwojaW8uZXN0YWZldHRlLmNpLnBy",
            "b3Rvcy5jb250cmFjdHMudjFaPGdpdGh1Yi5jb20vZXN0YWZldHRlL2VzdGFm",
            "ZXR0ZS1jaS1wcm90b3MtZ29sYW5nL2NvbnRyYWN0c192MaoCGUVzdGFmZXR0",
            "ZS5DSS5Db250cmFjdHMuVjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Estafette.CI.Manifest.V1.EstafetteEventReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Estafette.CI.Contracts.V1.Release), global::Estafette.CI.Contracts.V1.Release.Parser, new[]{ "Name", "Action", "Id", "RepoSource", "RepoOwner", "ReleaseVersion", "ReleaseStatus", "Events", "InsertedAt", "UpdatedAt", "Duration" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Release : pb::IMessage<Release> {
    private static readonly pb::MessageParser<Release> _parser = new pb::MessageParser<Release>(() => new Release());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Release> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Estafette.CI.Contracts.V1.ReleaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Release() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Release(Release other) : this() {
      name_ = other.name_;
      action_ = other.action_;
      id_ = other.id_;
      repoSource_ = other.repoSource_;
      repoOwner_ = other.repoOwner_;
      releaseVersion_ = other.releaseVersion_;
      releaseStatus_ = other.releaseStatus_;
      events_ = other.events_.Clone();
      insertedAt_ = other.insertedAt_ != null ? other.insertedAt_.Clone() : null;
      updatedAt_ = other.updatedAt_ != null ? other.updatedAt_.Clone() : null;
      duration_ = other.duration_ != null ? other.duration_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Release Clone() {
      return new Release(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 2;
    private string action_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Action {
      get { return action_; }
      set {
        action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "repo_source" field.</summary>
    public const int RepoSourceFieldNumber = 4;
    private string repoSource_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RepoSource {
      get { return repoSource_; }
      set {
        repoSource_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "repo_owner" field.</summary>
    public const int RepoOwnerFieldNumber = 5;
    private string repoOwner_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string RepoOwner {
      get { return repoOwner_; }
      set {
        repoOwner_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "release_version" field.</summary>
    public const int ReleaseVersionFieldNumber = 6;
    private string releaseVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ReleaseVersion {
      get { return releaseVersion_; }
      set {
        releaseVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "release_status" field.</summary>
    public const int ReleaseStatusFieldNumber = 7;
    private string releaseStatus_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ReleaseStatus {
      get { return releaseStatus_; }
      set {
        releaseStatus_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Estafette.CI.Manifest.V1.EstafetteEvent> _repeated_events_codec
        = pb::FieldCodec.ForMessage(66, global::Estafette.CI.Manifest.V1.EstafetteEvent.Parser);
    private readonly pbc::RepeatedField<global::Estafette.CI.Manifest.V1.EstafetteEvent> events_ = new pbc::RepeatedField<global::Estafette.CI.Manifest.V1.EstafetteEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Estafette.CI.Manifest.V1.EstafetteEvent> Events {
      get { return events_; }
    }

    /// <summary>Field number for the "inserted_at" field.</summary>
    public const int InsertedAtFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp insertedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp InsertedAt {
      get { return insertedAt_; }
      set {
        insertedAt_ = value;
      }
    }

    /// <summary>Field number for the "updated_at" field.</summary>
    public const int UpdatedAtFieldNumber = 10;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updatedAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdatedAt {
      get { return updatedAt_; }
      set {
        updatedAt_ = value;
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 11;
    private global::Google.Protobuf.WellKnownTypes.Duration duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Duration Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Release);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Release other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Action != other.Action) return false;
      if (Id != other.Id) return false;
      if (RepoSource != other.RepoSource) return false;
      if (RepoOwner != other.RepoOwner) return false;
      if (ReleaseVersion != other.ReleaseVersion) return false;
      if (ReleaseStatus != other.ReleaseStatus) return false;
      if(!events_.Equals(other.events_)) return false;
      if (!object.Equals(InsertedAt, other.InsertedAt)) return false;
      if (!object.Equals(UpdatedAt, other.UpdatedAt)) return false;
      if (!object.Equals(Duration, other.Duration)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Action.Length != 0) hash ^= Action.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (RepoSource.Length != 0) hash ^= RepoSource.GetHashCode();
      if (RepoOwner.Length != 0) hash ^= RepoOwner.GetHashCode();
      if (ReleaseVersion.Length != 0) hash ^= ReleaseVersion.GetHashCode();
      if (ReleaseStatus.Length != 0) hash ^= ReleaseStatus.GetHashCode();
      hash ^= events_.GetHashCode();
      if (insertedAt_ != null) hash ^= InsertedAt.GetHashCode();
      if (updatedAt_ != null) hash ^= UpdatedAt.GetHashCode();
      if (duration_ != null) hash ^= Duration.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Action.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Action);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Id);
      }
      if (RepoSource.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(RepoSource);
      }
      if (RepoOwner.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(RepoOwner);
      }
      if (ReleaseVersion.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ReleaseVersion);
      }
      if (ReleaseStatus.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(ReleaseStatus);
      }
      events_.WriteTo(output, _repeated_events_codec);
      if (insertedAt_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(InsertedAt);
      }
      if (updatedAt_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(UpdatedAt);
      }
      if (duration_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Duration);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Action.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (RepoSource.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoSource);
      }
      if (RepoOwner.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RepoOwner);
      }
      if (ReleaseVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReleaseVersion);
      }
      if (ReleaseStatus.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ReleaseStatus);
      }
      size += events_.CalculateSize(_repeated_events_codec);
      if (insertedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(InsertedAt);
      }
      if (updatedAt_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdatedAt);
      }
      if (duration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Duration);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Release other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Action.Length != 0) {
        Action = other.Action;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.RepoSource.Length != 0) {
        RepoSource = other.RepoSource;
      }
      if (other.RepoOwner.Length != 0) {
        RepoOwner = other.RepoOwner;
      }
      if (other.ReleaseVersion.Length != 0) {
        ReleaseVersion = other.ReleaseVersion;
      }
      if (other.ReleaseStatus.Length != 0) {
        ReleaseStatus = other.ReleaseStatus;
      }
      events_.Add(other.events_);
      if (other.insertedAt_ != null) {
        if (insertedAt_ == null) {
          insertedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        InsertedAt.MergeFrom(other.InsertedAt);
      }
      if (other.updatedAt_ != null) {
        if (updatedAt_ == null) {
          updatedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdatedAt.MergeFrom(other.UpdatedAt);
      }
      if (other.duration_ != null) {
        if (duration_ == null) {
          duration_ = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        Duration.MergeFrom(other.Duration);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Action = input.ReadString();
            break;
          }
          case 26: {
            Id = input.ReadString();
            break;
          }
          case 34: {
            RepoSource = input.ReadString();
            break;
          }
          case 42: {
            RepoOwner = input.ReadString();
            break;
          }
          case 50: {
            ReleaseVersion = input.ReadString();
            break;
          }
          case 58: {
            ReleaseStatus = input.ReadString();
            break;
          }
          case 66: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
          case 74: {
            if (insertedAt_ == null) {
              insertedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(insertedAt_);
            break;
          }
          case 82: {
            if (updatedAt_ == null) {
              updatedAt_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(updatedAt_);
            break;
          }
          case 90: {
            if (duration_ == null) {
              duration_ = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(duration_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
